"""add_unique_constraints_to_tenants

Revision ID: 2ffd2ad1ba8c
Revises: 38ed6337feaf
Create Date: 2025-10-06 18:54:17.223037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffd2ad1ba8c'
down_revision: Union[str, None] = '38ed6337feaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_unique_constraint('uq_tenant_email', 'tenants', ['email'])
    op.create_unique_constraint('uq_tenant_phone', 'tenants', ['phone'])
    op.create_unique_constraint('uq_tenant_school_name_address', 'tenants', ['school_name', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_school_name_address', 'tenants', type_='unique')
    op.drop_constraint('uq_tenant_phone', 'tenants', type_='unique')
    op.drop_constraint('uq_tenant_email', 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    # ### end Alembic commands ###
