"""remove_unwanted_tenant_fields

Revision ID: 312b6ac4e75e
Revises: 81dae1fc3e13
Create Date: 2025-10-27 16:24:31.134469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '312b6ac4e75e'
down_revision: Union[str, None] = '81dae1fc3e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_alerts_created_at'), 'attendance_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_alerts_is_deleted'), 'attendance_alerts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_policies_created_at'), 'attendance_policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_policies_is_deleted'), 'attendance_policies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_reports_created_at'), 'attendance_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_reports_is_deleted'), 'attendance_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_summaries_created_at'), 'attendance_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_summaries_is_deleted'), 'attendance_summaries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendances_created_at'), 'attendances', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendances_is_deleted'), 'attendances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_class_timetables_created_at'), 'class_timetables', ['created_at'], unique=False)
    op.create_index(op.f('ix_class_timetables_is_deleted'), 'class_timetables', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_classes_created_at'), 'classes', ['created_at'], unique=False)
    op.create_index(op.f('ix_classes_is_deleted'), 'classes', ['is_deleted'], unique=False)
    op.create_unique_constraint('uq_class_identity', 'classes', ['tenant_id', 'class_name', 'section', 'academic_year'])
    op.create_index(op.f('ix_enrollments_created_at'), 'enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrollments_is_deleted'), 'enrollments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_master_timetables_created_at'), 'master_timetables', ['created_at'], unique=False)
    op.create_index(op.f('ix_master_timetables_is_deleted'), 'master_timetables', ['is_deleted'], unique=False)
    op.alter_column('notification_batches', 'created_by_type',
               existing_type=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               type_=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_notification_batches_created_at'), 'notification_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_batches_is_deleted'), 'notification_batches', ['is_deleted'], unique=False)
    op.alter_column('notification_delivery_logs', 'channel',
               existing_type=postgresql.ENUM('IN_APP', 'EMAIL', 'SMS', 'PUSH', 'WHATSAPP', 'SLACK', name='deliverychannel'),
               type_=sa.Enum('in_app', 'email', 'sms', 'push', 'whatsapp', 'slack', name='deliverychannel', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_notification_delivery_logs_created_at'), 'notification_delivery_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_is_deleted'), 'notification_delivery_logs', ['is_deleted'], unique=False)
    op.alter_column('notification_groups', 'created_by_type',
               existing_type=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               type_=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_notification_groups_created_at'), 'notification_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_groups_is_deleted'), 'notification_groups', ['is_deleted'], unique=False)
    op.alter_column('notification_preferences', 'notification_type',
               existing_type=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               type_=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'min_priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               nullable=False)
    op.create_index(op.f('ix_notification_preferences_created_at'), 'notification_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_preferences_is_deleted'), 'notification_preferences', ['is_deleted'], unique=False)
    op.alter_column('notification_recipients', 'status',
               existing_type=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus'),
               type_=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus', native_enum=False),
               nullable=False)
    op.create_index(op.f('ix_notification_recipients_created_at'), 'notification_recipients', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_schedules_created_at'), 'notification_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_schedules_is_deleted'), 'notification_schedules', ['is_deleted'], unique=False)
    op.alter_column('notification_templates', 'created_by_type',
               existing_type=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               type_=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notification_templates', 'notification_type',
               existing_type=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               type_=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notification_templates', 'default_priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               nullable=False)
    op.create_index(op.f('ix_notification_templates_created_at'), 'notification_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_templates_is_deleted'), 'notification_templates', ['is_deleted'], unique=False)
    op.alter_column('notifications', 'sender_type',
               existing_type=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               type_=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               type_=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               type_=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               nullable=False)
    op.alter_column('notifications', 'recipient_type',
               existing_type=postgresql.ENUM('individual', 'class', 'grade', 'all_students', 'all_teachers', 'all_staff', 'department', 'custom_group', 'parents', 'all_users', name='recipienttype'),
               type_=sa.Enum('individual', 'class', 'grade', 'all_students', 'all_teachers', 'all_staff', 'department', 'custom_group', 'parents', 'all_users', name='recipienttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus'),
               type_=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus', native_enum=False),
               nullable=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_periods_created_at'), 'periods', ['created_at'], unique=False)
    op.create_index(op.f('ix_periods_is_deleted'), 'periods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_schedule_entries_created_at'), 'schedule_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_entries_is_deleted'), 'schedule_entries', ['is_deleted'], unique=False)
    op.drop_column('schedule_entries', 'original_teacher_name')
    op.drop_column('schedule_entries', 'location_notes')
    op.drop_column('schedule_entries', 'is_recurring')
    op.drop_column('schedule_entries', 'import_source')
    op.drop_column('schedule_entries', 'substitution_date')
    op.drop_column('schedule_entries', 'original_teacher_id')
    op.drop_column('schedule_entries', 'substitution_reason')
    op.drop_column('schedule_entries', 'expiry_date')
    op.drop_column('schedule_entries', 'effective_date')
    op.drop_column('schedule_entries', 'batch_id')
    op.drop_column('schedule_entries', 'notes')
    op.drop_column('schedule_entries', 'floor')
    op.drop_column('schedule_entries', 'attendance_required')
    op.drop_column('schedule_entries', 'room_capacity')
    op.create_index(op.f('ix_school_authorities_created_at'), 'school_authorities', ['created_at'], unique=False)
    op.create_index(op.f('ix_school_authorities_is_deleted'), 'school_authorities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_students_created_at'), 'students', ['created_at'], unique=False)
    op.create_index(op.f('ix_students_is_deleted'), 'students', ['is_deleted'], unique=False)
    op.drop_column('students', 'class_id')
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_index(op.f('ix_subjects_is_deleted'), 'subjects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_created_at'), 'teacher_timetables', ['created_at'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_is_deleted'), 'teacher_timetables', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teachers_created_at'), 'teachers', ['created_at'], unique=False)
    op.create_index(op.f('ix_teachers_is_deleted'), 'teachers', ['is_deleted'], unique=False)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('tenants', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.create_index('idx_active_code', 'tenants', ['is_active', 'school_code'], unique=False)
    op.create_index('idx_active_name', 'tenants', ['is_active', 'school_name'], unique=False)
    op.create_index('idx_created_at', 'tenants', ['created_at'], unique=False)
    op.create_index('idx_deleted_active', 'tenants', ['is_deleted', 'is_active'], unique=False)
    op.create_index('idx_email_active', 'tenants', ['email', 'is_active'], unique=False)
    op.create_index('idx_phone_active', 'tenants', ['phone', 'is_active'], unique=False)
    op.create_index('idx_school_type_active', 'tenants', ['school_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_unique_constraint('uq_tenant_school_code', 'tenants', ['school_code'])
    op.drop_column('tenants', 'academic_year_start')
    op.drop_column('tenants', 'current_enrollment')
    op.drop_column('tenants', 'total_students')
    op.drop_column('tenants', 'academic_year_end')
    op.drop_column('tenants', 'total_teachers')
    op.drop_column('tenants', 'total_staff')
    op.create_index(op.f('ix_timetable_audit_logs_created_at'), 'timetable_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_timetable_audit_logs_is_deleted'), 'timetable_audit_logs', ['is_deleted'], unique=False)
    op.drop_column('timetable_audit_logs', 'user_role')
    op.drop_column('timetable_audit_logs', 'user_agent')
    op.drop_column('timetable_audit_logs', 'performed_by_name')
    op.drop_column('timetable_audit_logs', 'ip_address')
    op.drop_column('timetable_audit_logs', 'new_values')
    op.drop_column('timetable_audit_logs', 'old_values')
    op.drop_column('timetable_audit_logs', 'session_id')
    op.create_index(op.f('ix_timetable_conflicts_created_at'), 'timetable_conflicts', ['created_at'], unique=False)
    op.create_index(op.f('ix_timetable_conflicts_is_deleted'), 'timetable_conflicts', ['is_deleted'], unique=False)
    op.drop_constraint('timetable_conflicts_schedule_entry_1_id_fkey', 'timetable_conflicts', type_='foreignkey')
    op.drop_constraint('timetable_conflicts_schedule_entry_2_id_fkey', 'timetable_conflicts', type_='foreignkey')
    op.drop_column('timetable_conflicts', 'resolution_notes')
    op.drop_column('timetable_conflicts', 'schedule_entry_2_id')
    op.drop_column('timetable_conflicts', 'schedule_entry_1_id')
    op.drop_column('timetable_conflicts', 'period_number')
    op.drop_column('timetable_conflicts', 'conflict_data')
    op.drop_column('timetable_conflicts', 'resolution_action')
    op.drop_column('timetable_conflicts', 'room_number')
    op.drop_column('timetable_conflicts', 'resolved_by')
    op.drop_column('timetable_conflicts', 'resolved_date')
    op.drop_column('timetable_conflicts', 'auto_resolve')
    op.drop_column('timetable_conflicts', 'teacher_id')
    op.drop_column('timetable_conflicts', 'day_of_week')
    op.drop_column('timetable_conflicts', 'class_id')
    op.drop_column('timetable_conflicts', 'detected_by')
    op.create_index(op.f('ix_timetable_templates_created_at'), 'timetable_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_timetable_templates_is_deleted'), 'timetable_templates', ['is_deleted'], unique=False)
    op.drop_column('timetable_templates', 'usage_count')
    op.drop_column('timetable_templates', 'last_used')
    op.drop_column('timetable_templates', 'is_public')
    op.drop_column('timetable_templates', 'description')
    op.drop_column('timetable_templates', 'created_by')
    op.drop_column('timetable_templates', 'grade_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_templates', sa.Column('grade_levels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('timetable_templates', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('timetable_templates', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('timetable_templates', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('timetable_templates', sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('timetable_templates', sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_timetable_templates_is_deleted'), table_name='timetable_templates')
    op.drop_index(op.f('ix_timetable_templates_created_at'), table_name='timetable_templates')
    op.add_column('timetable_conflicts', sa.Column('detected_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('day_of_week', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('auto_resolve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('resolved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('room_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('resolution_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('conflict_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('period_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('schedule_entry_1_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('schedule_entry_2_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timetable_conflicts', sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('timetable_conflicts_schedule_entry_2_id_fkey', 'timetable_conflicts', 'schedule_entries', ['schedule_entry_2_id'], ['id'])
    op.create_foreign_key('timetable_conflicts_schedule_entry_1_id_fkey', 'timetable_conflicts', 'schedule_entries', ['schedule_entry_1_id'], ['id'])
    op.drop_index(op.f('ix_timetable_conflicts_is_deleted'), table_name='timetable_conflicts')
    op.drop_index(op.f('ix_timetable_conflicts_created_at'), table_name='timetable_conflicts')
    op.add_column('timetable_audit_logs', sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('performed_by_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('timetable_audit_logs', sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_timetable_audit_logs_is_deleted'), table_name='timetable_audit_logs')
    op.drop_index(op.f('ix_timetable_audit_logs_created_at'), table_name='timetable_audit_logs')
    op.add_column('tenants', sa.Column('total_staff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_teachers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('academic_year_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_students', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('current_enrollment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('academic_year_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_tenant_school_code', 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index('idx_school_type_active', table_name='tenants')
    op.drop_index('idx_phone_active', table_name='tenants')
    op.drop_index('idx_email_active', table_name='tenants')
    op.drop_index('idx_deleted_active', table_name='tenants')
    op.drop_index('idx_created_at', table_name='tenants')
    op.drop_index('idx_active_name', table_name='tenants')
    op.drop_index('idx_active_code', table_name='tenants')
    op.alter_column('tenants', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tenants', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_teachers_is_deleted'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_created_at'), table_name='teachers')
    op.drop_index(op.f('ix_teacher_timetables_is_deleted'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_teacher_timetables_created_at'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_subjects_is_deleted'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.add_column('students', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_is_deleted'), table_name='students')
    op.drop_index(op.f('ix_students_created_at'), table_name='students')
    op.drop_index(op.f('ix_school_authorities_is_deleted'), table_name='school_authorities')
    op.drop_index(op.f('ix_school_authorities_created_at'), table_name='school_authorities')
    op.add_column('schedule_entries', sa.Column('room_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('attendance_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('floor', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('substitution_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('original_teacher_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('substitution_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('import_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('location_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schedule_entries', sa.Column('original_teacher_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_schedule_entries_is_deleted'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_created_at'), table_name='schedule_entries')
    op.drop_index(op.f('ix_periods_is_deleted'), table_name='periods')
    op.drop_index(op.f('ix_periods_created_at'), table_name='periods')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'status',
               existing_type=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus'),
               nullable=True)
    op.alter_column('notifications', 'recipient_type',
               existing_type=sa.Enum('individual', 'class', 'grade', 'all_students', 'all_teachers', 'all_staff', 'department', 'custom_group', 'parents', 'all_users', name='recipienttype', native_enum=False),
               type_=postgresql.ENUM('individual', 'class', 'grade', 'all_students', 'all_teachers', 'all_staff', 'department', 'custom_group', 'parents', 'all_users', name='recipienttype'),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               nullable=True)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               type_=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'sender_type',
               existing_type=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               type_=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_templates_is_deleted'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_created_at'), table_name='notification_templates')
    op.alter_column('notification_templates', 'default_priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               nullable=True)
    op.alter_column('notification_templates', 'notification_type',
               existing_type=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               type_=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notification_templates', 'created_by_type',
               existing_type=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               type_=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_schedules_is_deleted'), table_name='notification_schedules')
    op.drop_index(op.f('ix_notification_schedules_created_at'), table_name='notification_schedules')
    op.drop_index(op.f('ix_notification_recipients_created_at'), table_name='notification_recipients')
    op.alter_column('notification_recipients', 'status',
               existing_type=sa.Enum('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'scheduled', 'sent', 'delivered', 'read', 'archived', 'failed', 'cancelled', name='notificationstatus'),
               nullable=True)
    op.drop_index(op.f('ix_notification_preferences_is_deleted'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_created_at'), table_name='notification_preferences')
    op.alter_column('notification_preferences', 'min_priority',
               existing_type=sa.Enum('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority', native_enum=False),
               type_=postgresql.ENUM('low', 'normal', 'high', 'urgent', 'critical', name='notificationpriority'),
               nullable=True)
    op.alter_column('notification_preferences', 'notification_type',
               existing_type=sa.Enum('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype', native_enum=False),
               type_=postgresql.ENUM('announcement', 'urgent', 'assignment', 'grade', 'attendance', 'event', 'reminder', 'disciplinary', 'system', 'personal', 'maintenance', 'holiday', name='notificationtype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_groups_is_deleted'), table_name='notification_groups')
    op.drop_index(op.f('ix_notification_groups_created_at'), table_name='notification_groups')
    op.alter_column('notification_groups', 'created_by_type',
               existing_type=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               type_=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_delivery_logs_is_deleted'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_created_at'), table_name='notification_delivery_logs')
    op.alter_column('notification_delivery_logs', 'channel',
               existing_type=sa.Enum('in_app', 'email', 'sms', 'push', 'whatsapp', 'slack', name='deliverychannel', native_enum=False),
               type_=postgresql.ENUM('IN_APP', 'EMAIL', 'SMS', 'PUSH', 'WHATSAPP', 'SLACK', name='deliverychannel'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_batches_is_deleted'), table_name='notification_batches')
    op.drop_index(op.f('ix_notification_batches_created_at'), table_name='notification_batches')
    op.alter_column('notification_batches', 'created_by_type',
               existing_type=sa.Enum('school_authority', 'teacher', 'system', 'admin', name='sendertype', native_enum=False),
               type_=postgresql.ENUM('school_authority', 'teacher', 'system', 'admin', name='sendertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_master_timetables_is_deleted'), table_name='master_timetables')
    op.drop_index(op.f('ix_master_timetables_created_at'), table_name='master_timetables')
    op.drop_index(op.f('ix_enrollments_is_deleted'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_created_at'), table_name='enrollments')
    op.drop_constraint('uq_class_identity', 'classes', type_='unique')
    op.drop_index(op.f('ix_classes_is_deleted'), table_name='classes')
    op.drop_index(op.f('ix_classes_created_at'), table_name='classes')
    op.drop_index(op.f('ix_class_timetables_is_deleted'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_created_at'), table_name='class_timetables')
    op.drop_index(op.f('ix_attendances_is_deleted'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_created_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendance_summaries_is_deleted'), table_name='attendance_summaries')
    op.drop_index(op.f('ix_attendance_summaries_created_at'), table_name='attendance_summaries')
    op.drop_index(op.f('ix_attendance_reports_is_deleted'), table_name='attendance_reports')
    op.drop_index(op.f('ix_attendance_reports_created_at'), table_name='attendance_reports')
    op.drop_index(op.f('ix_attendance_policies_is_deleted'), table_name='attendance_policies')
    op.drop_index(op.f('ix_attendance_policies_created_at'), table_name='attendance_policies')
    op.drop_index(op.f('ix_attendance_alerts_is_deleted'), table_name='attendance_alerts')
    op.drop_index(op.f('ix_attendance_alerts_created_at'), table_name='attendance_alerts')
    # ### end Alembic commands ###
