"""Add teachers table

Revision ID: 45fdba2ed580
Revises: a3427436a276
Create Date: 2025-10-14 04:14:26.850332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fdba2ed580'
down_revision: Union[str, None] = 'a3427436a276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('personal_info', sa.JSON(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('family_info', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('employment', sa.JSON(), nullable=True),
    sa.Column('academic_responsibilities', sa.JSON(), nullable=True),
    sa.Column('timetable', sa.JSON(), nullable=True),
    sa.Column('performance_evaluation', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teachers_tenant_id'), 'teachers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_tenant_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
