"""Add students table

Revision ID: 819aebbae4f0
Revises: 45fdba2ed580
Create Date: 2025-10-14 15:37:52.406258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819aebbae4f0'
down_revision: Union[str, None] = '45fdba2ed580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admission_number', sa.String(length=20), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('parent_info', sa.JSON(), nullable=True),
    sa.Column('health_medical_info', sa.JSON(), nullable=True),
    sa.Column('emergency_information', sa.JSON(), nullable=True),
    sa.Column('behavioral_disciplinary', sa.JSON(), nullable=True),
    sa.Column('extended_academic_info', sa.JSON(), nullable=True),
    sa.Column('enrollment_details', sa.JSON(), nullable=True),
    sa.Column('financial_info', sa.JSON(), nullable=True),
    sa.Column('extracurricular_social', sa.JSON(), nullable=True),
    sa.Column('attendance_engagement', sa.JSON(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_admission_number'), 'students', ['admission_number'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_admission_number'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
