"""add_charges_fields_to_tenants

Revision ID: 8d3590fa2f8e
Revises: 312b6ac4e75e
Create Date: 2025-10-27 16:38:51.096845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3590fa2f8e'
down_revision: Union[str, None] = '312b6ac4e75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add charges_applied column with default value first
    op.add_column('tenants', sa.Column('charges_applied', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE tenants SET charges_applied = false WHERE charges_applied IS NULL")
    # Make column NOT NULL
    op.alter_column('tenants', 'charges_applied', nullable=False)
    
    op.add_column('tenants', sa.Column('charges_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'charges_amount')
    op.drop_column('tenants', 'charges_applied')
    # ### end Alembic commands ###
