"""Create EduAssist tables - tenants and school authorities

Revision ID: a3427436a276
Revises: 
Create Date: 2025-10-11 04:29:33.365024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3427436a276'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('school_code', sa.String(length=10), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('principal_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('annual_tuition', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('registration_fee', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('total_teachers', sa.Integer(), nullable=True),
    sa.Column('total_staff', sa.Integer(), nullable=True),
    sa.Column('maximum_capacity', sa.Integer(), nullable=False),
    sa.Column('current_enrollment', sa.Integer(), nullable=True),
    sa.Column('school_type', sa.String(length=20), nullable=True),
    sa.Column('grade_levels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('academic_year_start', sa.DateTime(), nullable=True),
    sa.Column('academic_year_end', sa.DateTime(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('accreditation', sa.String(length=50), nullable=True),
    sa.Column('language_of_instruction', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_tenant_email'),
    sa.UniqueConstraint('phone', name='uq_tenant_phone'),
    sa.UniqueConstraint('school_name', 'address', name='uq_tenant_school_name_address')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_school_code'), 'tenants', ['school_code'], unique=True)
    op.create_index(op.f('ix_tenants_school_name'), 'tenants', ['school_name'], unique=False)
    op.create_table('school_authorities',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=False),
    sa.Column('authority_details', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('school_overview', sa.JSON(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_authorities_authority_id'), 'school_authorities', ['authority_id'], unique=False)
    op.create_index(op.f('ix_school_authorities_email'), 'school_authorities', ['email'], unique=True)
    op.create_index(op.f('ix_school_authorities_id'), 'school_authorities', ['id'], unique=False)
    op.create_index(op.f('ix_school_authorities_tenant_id'), 'school_authorities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_authorities_tenant_id'), table_name='school_authorities')
    op.drop_index(op.f('ix_school_authorities_id'), table_name='school_authorities')
    op.drop_index(op.f('ix_school_authorities_email'), table_name='school_authorities')
    op.drop_index(op.f('ix_school_authorities_authority_id'), table_name='school_authorities')
    op.drop_table('school_authorities')
    op.drop_index(op.f('ix_tenants_school_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_school_code'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
